#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup

* Gio's Tetris 

This is Gio's attempt to create a tetris game with
pygame. Honestly I know there are infinite other
attempts out there mostly success and so much
better examples but I still want to try it out, to
learn more how to use Python, and Pygame.

In any case I am having a ton of fun, which is
always good.

*Rules*, *Gameplay* and *History* [[https://en.wikipedia.org/wiki/Tetris][Here]]

** Commands

1. <UP> To change the disposition of the stone
2. <DOWN> To fasten the fall of the stone
3. <RIGHT> To move right the stone
4. <LEFT> To move left the stone

** Bugs

I know there are some bugs, which I will try to
remove. Here there is a list:

1. Sometimes the stone falls anyways into the grey
   already fallen stones
2. When it's GAMEOVER, it's very brutal to close
   the game.
3. If next up is Vertical stone, GAMEOVER doesn't work.
4. when dropping pieces from the far right, they
   sometimes overlap
5. when dropping the long piece in vertical in the
   middle it doesnt stop in the game window but
   continues going into the oblivion
6. sometimes it feels like a single button press
   results to double clicking.

** Code Optimization

The code requires optimization, it is very messy
right now.
